apiVersion: v1
kind: Service
metadata:
  name: apache2-service
  namespace: www
spec:
  type: NodePort
  selector:
    app: apache2
  ports:
  - name: port-1  # Provide a meaningful name for the first port
    protocol: TCP
    port: 20000
    targetPort: 25000
  - name: port-2  # Provide a meaningful name for the second port
    protocol: TCP
    port: 30000
    targetPort: 35000